### ISSUE TITLE
issue to write data on PI server

### ISSUE THREAD

**Issue by julienDuhart** [dataiku/dss-plugin-osisoft#28]
I tried the  plugin PI to wirte data on PI server from Dataiku
 
it does not work totally : the Value « column value » is well pasted but the time (timestamp "date" column) of the value is not considered. By default the plugin use the timestamp of the job date.
 
[TESTDATAWRITEPI.zip](https://github.com/dataiku/dss-plugin-osisoft/files/11381927/TESTDATAWRITEPI.zip)

**Comment by alexbourret** [comment]
Hi @julienDuhart ! Sorry for the delay as I missed the notification...
Could you provide a screenshot of the input dataset, showing the column header (name, storage and meaning) as well as the parsed date entry that is not accepted ? Something like this:
<img width="168" alt="Screenshot 2023-08-07 at 10 50 11" src="https://github.com/dataiku/dss-plugin-osisoft/assets/3763569/6ab1ba99-4c05-4f3d-ba49-922e3f754740">
This would help us reproduce the issue on our side...

**Comment by julienDuhart** [comment]
Thanks
